//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача не найдена, объект с таким id не существует.
        /// </summary>
        internal static string BLExceptionItemNotFind {
            get {
                return ResourceManager.GetString("BLExceptionItemNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обновить задачу, т.к. объект с таким id не существует.
        /// </summary>
        internal static string BLExceptionUpdateNotFindPrevious {
            get {
                return ResourceManager.GetString("BLExceptionUpdateNotFindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно установить для задачи статус &quot;Завершена&quot;, т.к. предыдущий статус должен быть &quot;Выполняется&quot; или &quot;Приостановлена&quot;.
        /// </summary>
        internal static string BLExceptionUpdateStatus {
            get {
                return ResourceManager.GetString("BLExceptionUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Наименование&quot; не указано.
        /// </summary>
        internal static string BLExceptionValidationCreateNoTitle {
            get {
                return ResourceManager.GetString("BLExceptionValidationCreateNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус &quot;Завершена&quot; не может быть установлен для новой задачи.
        /// </summary>
        internal static string BLExceptionValidationCreateStatusIs4 {
            get {
                return ResourceManager.GetString("BLExceptionValidationCreateStatusIs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус может быть только: &quot;Назначена&quot;, &quot;Выполняется&quot;, &quot;Приостановлена&quot;, &quot;Завершена&quot;.
        /// </summary>
        internal static string BLExceptionValidationIncorrectStatus {
            get {
                return ResourceManager.GetString("BLExceptionValidationIncorrectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Исполнители&quot; не указаны.
        /// </summary>
        internal static string BLExceptionValidationNullExecutors {
            get {
                return ResourceManager.GetString("BLExceptionValidationNullExecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить задачу, т.к. объект с таким id уже существует.
        /// </summary>
        internal static string RepositoryExceptionCreate {
            get {
                return ResourceManager.GetString("RepositoryExceptionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить задачу, т.к. объект с таким id не существует.
        /// </summary>
        internal static string RepositoryExceptionDelete {
            get {
                return ResourceManager.GetString("RepositoryExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обновить задачу, т.к. объект с таким id не существует.
        /// </summary>
        internal static string RepositoryExceptionUpdate {
            get {
                return ResourceManager.GetString("RepositoryExceptionUpdate", resourceCulture);
            }
        }
    }
}
